import sharp from "sharp";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const src = path.join(root, "public", "media", "logos", "crest-dark.png");
const out = path.join(root, "src", "lib", "crest-logo.ts");

// Compact, crisp crest for the PDF letterhead (drawn ~40pt tall; 220px is ample).
const buf = await sharp(src)
  .resize({ width: 220, fit: "inside", withoutEnlargement: true })
  .png({ compressionLevel: 9 })
  .toBuffer();

const meta = await sharp(buf).metadata();
const b64 = buf.toString("base64");

const file = `// AUTO-GENERATED by scripts/embed-crest.mjs — do not edit by hand.
// Compact transparent Rosewood Living crest (deep rosewood line art) for the PDF letterhead.
export const CREST_PNG_WIDTH = ${meta.width};
export const CREST_PNG_HEIGHT = ${meta.height};
export const CREST_PNG_BASE64 =
  "${b64}";
`;

writeFileSync(out, file);
console.log(`Wrote ${out} (${meta.width}x${meta.height}, ${(b64.length / 1024).toFixed(1)} KB base64)`);
